//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/ironcore-dev/metal-maintenance-operator/api"
	maintenancev1alpha1 "github.com/ironcore-dev/metal-maintenance-operator/api/maintenance/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettings) DeepCopyInto(out *BIOSSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettings.
func (in *BIOSSettings) DeepCopy() *BIOSSettings {
	if in == nil {
		return nil
	}
	out := new(BIOSSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsFlowStatus) DeepCopyInto(out *BIOSSettingsFlowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsFlowStatus.
func (in *BIOSSettingsFlowStatus) DeepCopy() *BIOSSettingsFlowStatus {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsList) DeepCopyInto(out *BIOSSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BIOSSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsList.
func (in *BIOSSettingsList) DeepCopy() *BIOSSettingsList {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsSet) DeepCopyInto(out *BIOSSettingsSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsSet.
func (in *BIOSSettingsSet) DeepCopy() *BIOSSettingsSet {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSSettingsSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsSetList) DeepCopyInto(out *BIOSSettingsSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BIOSSettingsSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsSetList.
func (in *BIOSSettingsSetList) DeepCopy() *BIOSSettingsSetList {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSSettingsSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsSetSpec) DeepCopyInto(out *BIOSSettingsSetSpec) {
	*out = *in
	in.BIOSSettingsTemplate.DeepCopyInto(&out.BIOSSettingsTemplate)
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsSetSpec.
func (in *BIOSSettingsSetSpec) DeepCopy() *BIOSSettingsSetSpec {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsSetStatus) DeepCopyInto(out *BIOSSettingsSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsSetStatus.
func (in *BIOSSettingsSetStatus) DeepCopy() *BIOSSettingsSetStatus {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsSpec) DeepCopyInto(out *BIOSSettingsSpec) {
	*out = *in
	in.BIOSSettingsTemplate.DeepCopyInto(&out.BIOSSettingsTemplate)
	if in.ServerMaintenanceRef != nil {
		in, out := &in.ServerMaintenanceRef, &out.ServerMaintenanceRef
		*out = new(apiv1alpha1.ObjectReference)
		**out = **in
	}
	if in.ServerRef != nil {
		in, out := &in.ServerRef, &out.ServerRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsSpec.
func (in *BIOSSettingsSpec) DeepCopy() *BIOSSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsStatus) DeepCopyInto(out *BIOSSettingsStatus) {
	*out = *in
	if in.FlowState != nil {
		in, out := &in.FlowState, &out.FlowState
		*out = make([]BIOSSettingsFlowStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsStatus.
func (in *BIOSSettingsStatus) DeepCopy() *BIOSSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSSettingsTemplate) DeepCopyInto(out *BIOSSettingsTemplate) {
	*out = *in
	in.SettingsTemplate.DeepCopyInto(&out.SettingsTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSSettingsTemplate.
func (in *BIOSSettingsTemplate) DeepCopy() *BIOSSettingsTemplate {
	if in == nil {
		return nil
	}
	out := new(BIOSSettingsTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersion) DeepCopyInto(out *BIOSVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersion.
func (in *BIOSVersion) DeepCopy() *BIOSVersion {
	if in == nil {
		return nil
	}
	out := new(BIOSVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionList) DeepCopyInto(out *BIOSVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BIOSVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionList.
func (in *BIOSVersionList) DeepCopy() *BIOSVersionList {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionSet) DeepCopyInto(out *BIOSVersionSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionSet.
func (in *BIOSVersionSet) DeepCopy() *BIOSVersionSet {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSVersionSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionSetList) DeepCopyInto(out *BIOSVersionSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BIOSVersionSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionSetList.
func (in *BIOSVersionSetList) DeepCopy() *BIOSVersionSetList {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BIOSVersionSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionSetSpec) DeepCopyInto(out *BIOSVersionSetSpec) {
	*out = *in
	in.ServerSelector.DeepCopyInto(&out.ServerSelector)
	in.BIOSVersionTemplate.DeepCopyInto(&out.BIOSVersionTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionSetSpec.
func (in *BIOSVersionSetSpec) DeepCopy() *BIOSVersionSetSpec {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionSetStatus) DeepCopyInto(out *BIOSVersionSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionSetStatus.
func (in *BIOSVersionSetStatus) DeepCopy() *BIOSVersionSetStatus {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionSpec) DeepCopyInto(out *BIOSVersionSpec) {
	*out = *in
	in.BIOSVersionTemplate.DeepCopyInto(&out.BIOSVersionTemplate)
	if in.ServerMaintenanceRef != nil {
		in, out := &in.ServerMaintenanceRef, &out.ServerMaintenanceRef
		*out = new(apiv1alpha1.ObjectReference)
		**out = **in
	}
	if in.ServerRef != nil {
		in, out := &in.ServerRef, &out.ServerRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionSpec.
func (in *BIOSVersionSpec) DeepCopy() *BIOSVersionSpec {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionStatus) DeepCopyInto(out *BIOSVersionStatus) {
	*out = *in
	if in.UpgradeTask != nil {
		in, out := &in.UpgradeTask, &out.UpgradeTask
		*out = new(api.Task)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionStatus.
func (in *BIOSVersionStatus) DeepCopy() *BIOSVersionStatus {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BIOSVersionTemplate) DeepCopyInto(out *BIOSVersionTemplate) {
	*out = *in
	if in.UpdatePolicy != nil {
		in, out := &in.UpdatePolicy, &out.UpdatePolicy
		*out = new(api.UpdatePolicy)
		**out = **in
	}
	in.Image.DeepCopyInto(&out.Image)
	if in.ServerMaintenancePolicy != nil {
		in, out := &in.ServerMaintenancePolicy, &out.ServerMaintenancePolicy
		*out = new(maintenancev1alpha1.ServerMaintenancePolicy)
		**out = **in
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(api.RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BIOSVersionTemplate.
func (in *BIOSVersionTemplate) DeepCopy() *BIOSVersionTemplate {
	if in == nil {
		return nil
	}
	out := new(BIOSVersionTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentJobsSummary) DeepCopyInto(out *ComponentJobsSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentJobsSummary.
func (in *ComponentJobsSummary) DeepCopy() *ComponentJobsSummary {
	if in == nil {
		return nil
	}
	out := new(ComponentJobsSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDell) DeepCopyInto(out *FirmwareUpdateDell) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDell.
func (in *FirmwareUpdateDell) DeepCopy() *FirmwareUpdateDell {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareUpdateDell) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDellList) DeepCopyInto(out *FirmwareUpdateDellList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FirmwareUpdateDell, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDellList.
func (in *FirmwareUpdateDellList) DeepCopy() *FirmwareUpdateDellList {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDellList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FirmwareUpdateDellList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDellSpec) DeepCopyInto(out *FirmwareUpdateDellSpec) {
	*out = *in
	in.FirmwareUpdateDellTemplate.DeepCopyInto(&out.FirmwareUpdateDellTemplate)
	if in.ServerMaintenanceRef != nil {
		in, out := &in.ServerMaintenanceRef, &out.ServerMaintenanceRef
		*out = new(apiv1alpha1.ObjectReference)
		**out = **in
	}
	if in.ServerMaintenancePolicy != nil {
		in, out := &in.ServerMaintenancePolicy, &out.ServerMaintenancePolicy
		*out = new(maintenancev1alpha1.ServerMaintenancePolicy)
		**out = **in
	}
	if in.ServerRef != nil {
		in, out := &in.ServerRef, &out.ServerRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(api.RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDellSpec.
func (in *FirmwareUpdateDellSpec) DeepCopy() *FirmwareUpdateDellSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDellSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDellStatus) DeepCopyInto(out *FirmwareUpdateDellStatus) {
	*out = *in
	if in.CheckJob != nil {
		in, out := &in.CheckJob, &out.CheckJob
		*out = new(RepositoryJob)
		**out = **in
	}
	if in.UpdateJob != nil {
		in, out := &in.UpdateJob, &out.UpdateJob
		*out = new(RepositoryJob)
		**out = **in
	}
	if in.ComponentJobs != nil {
		in, out := &in.ComponentJobs, &out.ComponentJobs
		*out = make([]RepositoryJob, len(*in))
		copy(*out, *in)
	}
	if in.ComponentJobsSummary != nil {
		in, out := &in.ComponentJobsSummary, &out.ComponentJobsSummary
		*out = new(ComponentJobsSummary)
		**out = **in
	}
	if in.BaselineJobIDs != nil {
		in, out := &in.BaselineJobIDs, &out.BaselineJobIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDellStatus.
func (in *FirmwareUpdateDellStatus) DeepCopy() *FirmwareUpdateDellStatus {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareUpdateDellTemplate) DeepCopyInto(out *FirmwareUpdateDellTemplate) {
	*out = *in
	in.Repository.DeepCopyInto(&out.Repository)
	if in.ApplySameVersions != nil {
		in, out := &in.ApplySameVersions, &out.ApplySameVersions
		*out = new(bool)
		**out = **in
	}
	if in.ApplyDowngradeVersions != nil {
		in, out := &in.ApplyDowngradeVersions, &out.ApplyDowngradeVersions
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareUpdateDellTemplate.
func (in *FirmwareUpdateDellTemplate) DeepCopy() *FirmwareUpdateDellTemplate {
	if in == nil {
		return nil
	}
	out := new(FirmwareUpdateDellTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryJob) DeepCopyInto(out *RepositoryJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryJob.
func (in *RepositoryJob) DeepCopy() *RepositoryJob {
	if in == nil {
		return nil
	}
	out := new(RepositoryJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.IgnoreCertWarning != nil {
		in, out := &in.IgnoreCertWarning, &out.IgnoreCertWarning
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}
