---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings
  - bmcsettingssets
  - bmcusers
  - bmcversions
  - bmcversionsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings/finalizers
  - bmcsettingssets/finalizers
  - bmcusers/finalizers
  - bmcversions/finalizers
  - bmcversionsets/finalizers
  verbs:
  - update
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings/status
  - bmcsettingssets/status
  - bmcusers/status
  - bmcversions/status
  - bmcversionsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/finalizers
  verbs:
  - update
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bmcs
  - servers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bmcs/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - bmcsecrets
  - serverbootconfigurations
  - serverclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings/finalizers
  verbs:
  - update
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings
  - biossettingssets
  - biosversions
  - biosversionsets
  - firmwareupdates
  - firmwareupdatesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings/finalizers
  - biossettingssets/finalizers
  - biosversions/finalizers
  - biosversionsets/finalizers
  - firmwareupdates/finalizers
  - firmwareupdatesets/finalizers
  verbs:
  - update
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings/status
  - biossettingssets/status
  - biosversions/status
  - biosversionsets/status
  - firmwareupdates/status
  - firmwareupdatesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/finalizers
  verbs:
  - update
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/status
  verbs:
  - get
  - patch
  - update
