//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/ironcore-dev/metal-maintenance-operator/api"
	apiv1alpha1 "github.com/ironcore-dev/metal-operator/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettings) DeepCopyInto(out *BMCSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettings.
func (in *BMCSettings) DeepCopy() *BMCSettings {
	if in == nil {
		return nil
	}
	out := new(BMCSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsApplyResultEntry) DeepCopyInto(out *BMCSettingsApplyResultEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsApplyResultEntry.
func (in *BMCSettingsApplyResultEntry) DeepCopy() *BMCSettingsApplyResultEntry {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsApplyResultEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsList) DeepCopyInto(out *BMCSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BMCSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsList.
func (in *BMCSettingsList) DeepCopy() *BMCSettingsList {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsSet) DeepCopyInto(out *BMCSettingsSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsSet.
func (in *BMCSettingsSet) DeepCopy() *BMCSettingsSet {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCSettingsSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsSetList) DeepCopyInto(out *BMCSettingsSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BMCSettingsSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsSetList.
func (in *BMCSettingsSetList) DeepCopy() *BMCSettingsSetList {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCSettingsSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsSetSpec) DeepCopyInto(out *BMCSettingsSetSpec) {
	*out = *in
	in.BMCSettingsTemplate.DeepCopyInto(&out.BMCSettingsTemplate)
	in.BMCSelector.DeepCopyInto(&out.BMCSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsSetSpec.
func (in *BMCSettingsSetSpec) DeepCopy() *BMCSettingsSetSpec {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsSetStatus) DeepCopyInto(out *BMCSettingsSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsSetStatus.
func (in *BMCSettingsSetStatus) DeepCopy() *BMCSettingsSetStatus {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsSpec) DeepCopyInto(out *BMCSettingsSpec) {
	*out = *in
	in.BMCSettingsTemplate.DeepCopyInto(&out.BMCSettingsTemplate)
	if in.ServerMaintenanceRefs != nil {
		in, out := &in.ServerMaintenanceRefs, &out.ServerMaintenanceRefs
		*out = make([]api.ServerMaintenanceRefItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BMCRef != nil {
		in, out := &in.BMCRef, &out.BMCRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsSpec.
func (in *BMCSettingsSpec) DeepCopy() *BMCSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsStatus) DeepCopyInto(out *BMCSettingsStatus) {
	*out = *in
	if in.AppliedETags != nil {
		in, out := &in.AppliedETags, &out.AppliedETags
		*out = make(map[string]BMCSettingsApplyResultEntry, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsStatus.
func (in *BMCSettingsStatus) DeepCopy() *BMCSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCSettingsTemplate) DeepCopyInto(out *BMCSettingsTemplate) {
	*out = *in
	in.SettingsTemplate.DeepCopyInto(&out.SettingsTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCSettingsTemplate.
func (in *BMCSettingsTemplate) DeepCopy() *BMCSettingsTemplate {
	if in == nil {
		return nil
	}
	out := new(BMCSettingsTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUser) DeepCopyInto(out *BMCUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUser.
func (in *BMCUser) DeepCopy() *BMCUser {
	if in == nil {
		return nil
	}
	out := new(BMCUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserList) DeepCopyInto(out *BMCUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BMCUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserList.
func (in *BMCUserList) DeepCopy() *BMCUserList {
	if in == nil {
		return nil
	}
	out := new(BMCUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserSpec) DeepCopyInto(out *BMCUserSpec) {
	*out = *in
	if in.RotationPeriod != nil {
		in, out := &in.RotationPeriod, &out.RotationPeriod
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.BMCSecretRef != nil {
		in, out := &in.BMCSecretRef, &out.BMCSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.BMCRef != nil {
		in, out := &in.BMCRef, &out.BMCRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserSpec.
func (in *BMCUserSpec) DeepCopy() *BMCUserSpec {
	if in == nil {
		return nil
	}
	out := new(BMCUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCUserStatus) DeepCopyInto(out *BMCUserStatus) {
	*out = *in
	if in.EffectiveBMCSecretRef != nil {
		in, out := &in.EffectiveBMCSecretRef, &out.EffectiveBMCSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.LastRotation != nil {
		in, out := &in.LastRotation, &out.LastRotation
		*out = (*in).DeepCopy()
	}
	if in.PasswordExpiration != nil {
		in, out := &in.PasswordExpiration, &out.PasswordExpiration
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCUserStatus.
func (in *BMCUserStatus) DeepCopy() *BMCUserStatus {
	if in == nil {
		return nil
	}
	out := new(BMCUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersion) DeepCopyInto(out *BMCVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersion.
func (in *BMCVersion) DeepCopy() *BMCVersion {
	if in == nil {
		return nil
	}
	out := new(BMCVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionList) DeepCopyInto(out *BMCVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BMCVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionList.
func (in *BMCVersionList) DeepCopy() *BMCVersionList {
	if in == nil {
		return nil
	}
	out := new(BMCVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionSet) DeepCopyInto(out *BMCVersionSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionSet.
func (in *BMCVersionSet) DeepCopy() *BMCVersionSet {
	if in == nil {
		return nil
	}
	out := new(BMCVersionSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCVersionSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionSetList) DeepCopyInto(out *BMCVersionSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BMCVersionSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionSetList.
func (in *BMCVersionSetList) DeepCopy() *BMCVersionSetList {
	if in == nil {
		return nil
	}
	out := new(BMCVersionSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BMCVersionSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionSetSpec) DeepCopyInto(out *BMCVersionSetSpec) {
	*out = *in
	in.BMCSelector.DeepCopyInto(&out.BMCSelector)
	in.BMCVersionTemplate.DeepCopyInto(&out.BMCVersionTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionSetSpec.
func (in *BMCVersionSetSpec) DeepCopy() *BMCVersionSetSpec {
	if in == nil {
		return nil
	}
	out := new(BMCVersionSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionSetStatus) DeepCopyInto(out *BMCVersionSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionSetStatus.
func (in *BMCVersionSetStatus) DeepCopy() *BMCVersionSetStatus {
	if in == nil {
		return nil
	}
	out := new(BMCVersionSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionSpec) DeepCopyInto(out *BMCVersionSpec) {
	*out = *in
	in.BMCVersionTemplate.DeepCopyInto(&out.BMCVersionTemplate)
	if in.ServerMaintenanceRefs != nil {
		in, out := &in.ServerMaintenanceRefs, &out.ServerMaintenanceRefs
		*out = make([]apiv1alpha1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.BMCRef != nil {
		in, out := &in.BMCRef, &out.BMCRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionSpec.
func (in *BMCVersionSpec) DeepCopy() *BMCVersionSpec {
	if in == nil {
		return nil
	}
	out := new(BMCVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionStatus) DeepCopyInto(out *BMCVersionStatus) {
	*out = *in
	if in.UpgradeTask != nil {
		in, out := &in.UpgradeTask, &out.UpgradeTask
		*out = new(api.Task)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionStatus.
func (in *BMCVersionStatus) DeepCopy() *BMCVersionStatus {
	if in == nil {
		return nil
	}
	out := new(BMCVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCVersionTemplate) DeepCopyInto(out *BMCVersionTemplate) {
	*out = *in
	if in.UpdatePolicy != nil {
		in, out := &in.UpdatePolicy, &out.UpdatePolicy
		*out = new(api.UpdatePolicy)
		**out = **in
	}
	in.Image.DeepCopyInto(&out.Image)
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(api.RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCVersionTemplate.
func (in *BMCVersionTemplate) DeepCopy() *BMCVersionTemplate {
	if in == nil {
		return nil
	}
	out := new(BMCVersionTemplate)
	in.DeepCopyInto(out)
	return out
}
